# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  push:
    branches: [ "master" ]
    tags: ["*"]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
    - uses: actions/checkout@v7
      with:
        submodules: true

    - name: Install verilator
      uses: veryl-lang/setup-verilator@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v7
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e '.[test]'

    - name: Lint with ruff
      uses: astral-sh/ruff-action@v1

    - name: Test with pytest
      run: pytest --cov .

    - name: Upload coverage to codecov
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        pip install codecov
        codecov || true

  build:
    needs:
      - test
    name: Build distributions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: true

      - uses: actions/setup-python@v7
        name: Install Python
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install -U build

      - name: Build
        run: python -m build

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: python-package-distributions
          path: |
            dist/*.tar.gz
            dist/*.whl

      - name: Release
        uses: softprops/action-gh-release@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/*.tar.gz
            dist/*.whl
          generate_release_notes: true

  deploy:
    needs:
      - build

    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write

    # Only publish when a tag is pushed.
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v8
        with:
          name: python-package-distributions
          path: dist

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1